export const Vegtableslist = [
    {
        id: 1,
        title: "Wholewheat bread",
        price: "1.10 $/piece",
        kg: "~80 gr/piece",
        images: require("../assets/bread1.jpg"),
        discount: '35%',
        description: "Bread is a staple food prepared from a dough of flour (usually wheat) and water, usually by baking. Throughout recorded history and around the world, it has been an important part of many cultures' diet. It is one of the oldest human-made foods, having been of significance since the dawn of agriculture, and plays an essential role in both religious rituals and secular culture.",
        descriptiontitle: "Spain",
        types: "Wholewheat bread",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 2,
        title: "Sourdough brea",
        price: "1.85 € / piece",
        kg: "~10 gr/piece",
        images: require("../assets/bread2.jpg"),
        descriptiontitle: "Spain",
        descriptiontitle: "Spain",
        discount: '15%',
        types: "Sourdough brea",
        description: "Bread is one of the oldest prepared foods. Evidence from 30,000 years ago in Europe and Australia revealed starch residue on rocks used for pounding plants.[1][2] It is possible that during this time, starch extract from the roots of plants, such as cattails and ferns, was spread on a flat rock, placed over a fire and cooked into a primitive form of flatbread.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 3,
        title: "Pumpernickel bread",
        price: "1.45 € / piece",
        images: require("../assets/bread3.jpg"),
        kg: "~230 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Pumpernickel bread",
        description: "Salt (sodium chloride) is very often added to enhance flavor and restrict yeast activity. It also affects the crumb and the overall texture by stabilizing and strengthening[43] the gluten. Some artisan bakers forego early addition of salt to the dough, whether wholemeal or refined, and wait until after a 20-minute rest to allow the dough to autolyse.[44",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 4,
        title: "Multigrain bread.",
        price: "1.996 € / piece",
        images: require("../assets/bread4.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '50%',
        types: "Multigrain bread.",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 5,
        title: "Lefse (Norway)",
        price: "1.994 € / piece",
        images: require("../assets/newbread1.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Lefse (Norway)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 6,
        title: "Lefse (Norway)",
        price: "1.994 € / piece",
        images: require("../assets/newbread1.jpg"),
        kg: "~200 gr/piece",
        discount: '3%',
        descriptiontitle: "Spain",
        types: "Lefse (Norway)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 7,
        title: "Lefse (Norway)",
        price: "1.994 € / piece",
        images: require("../assets/newbread1.jpg"),
        kg: "~200 gr/piece",
        discount: '10%',
        types: "Lefse (Norway)",
        descriptiontitle: "Spain",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 8,
        title: "Lefse (Norway)",
        price: "1.994 € / piece",
        images: require("../assets/newbread1.jpg"),
        kg: "~200 gr/piece",
        discount: '20%',
        types: "Lefse (Norway)",
        descriptiontitle: "Spain",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 9,
        title: "Lefse (Norway)",
        price: "1.994 € / piece",
        images: require("../assets/newbread1.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '25%',
        types: "Lefse (Norway)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 10,
        title: "Bagel (Poland/Jewish)",
        price: "1.992 € / piece",
        images: require("../assets/newbred2.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '30%',
        types: "Bagel (Poland/Jewish)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 11,
        title: "Bagel (Poland/Jewish) ",
        price: "1.992 € / piece",
        images: require("../assets/newbred2.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Bagel (Poland/Jewish) ",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",


        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 12,
        title: "Bagel (Poland/Jewish) ",
        price: "1.992 € / piece",
        images: require("../assets/newbred2.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Bagel (Poland/Jewish) ",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 13,
        title: "Hala (Poland)",
        price: "1.991 € / piece",
        images: require("../assets/newveg3.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Hala (Poland)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 14,
        title: "Bolillo (Mexico)",
        price: "1.99 € / piece",
        images: require("../assets/newveg4.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Bolillo (Mexico)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 15,
        title: "Bolillo",
        price: "1.99 € / piece",
        images: require("../assets/newveg4.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Bolillo",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 16,
        title: "Bolillo",
        price: "1.99 € / piece",
        images: require("../assets/newveg4.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '70%',
        types: "Bolillo",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",


        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 17,
        title: "Bolillo",
        price: "1.99 € / piece",
        images: require("../assets/newveg4.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Bolillo",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,



    },
    {
        id: 18,
        title: "Bolillo",
        price: "1.99 € / piece",
        images: require("../assets/newveg4.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Bolillo",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 19,
        title: "Bolillo",
        price: "1.99 € / piece",
        images: require("../assets/newveg4.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Bolillo",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",


        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 20,
        title: "Mantou (China)",
        price: "18.99 € / piece",
        images: require("../assets/newbread5.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Mantou (China)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 21,
        title: "Mantou (China)",
        price: "18.99 € / piece",
        images: require("../assets/newbread5.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Mantou (China)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 22,
        title: "Mantou (China)",
        price: "18.99 € / piece",
        images: require("../assets/newbread5.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Mantou (China)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 23,
        title: "Injera (Ethiopia)",
        price: "341.99 € / piece",
        images: require("../assets/newbread6.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        types: "Injera (Ethiopia)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",


        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 24,
        title: "Lavash (Armenia).",
        price: "81.99 € / piece",
        images: require("../assets/newbread7.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '52%',
        types: "Lavash (Armenia)",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 25,
        title: "Sourdough (Various).",
        price: "71.99 € / piece",
        images: require("../assets/newbread8.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Sourdough (Various).",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",


        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 26,
        title: "Tortilla (Mexico).",
        price: "1.599 € / piece",
        images: require("../assets/newbread9.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Tortilla (Mexico).",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 27,
        title: "Ciabatta (Italy) bread.",
        price: "16.99 € / piece",
        images: require("../assets/newbread11.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Ciabatta (Italy) bread.",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 28,
        title: "Naan (India) bread.",
        price: "1.699 € / piece",
        images: require("../assets/newbread12.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        types: "Naan (India) bread.",
        discount: '5%',
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 29,
        title: "Multigrain bread",
        price: "153.99 € / piece",
        images: require("../assets/newbread13.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        types: "Multigrain bread",
        discount: '5%',
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 30,
        title: "Multigrain bread",
        price: "153.99 € / piece",
        images: require("../assets/newbread13.jpg"),
        kg: "~200 gr/piece",
        discount: '5%',
        descriptiontitle: "Spain",
        types: "Multigrain bread",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 31,
        title: "Multigrain bread",
        price: "153.99 € / piece",
        images: require("../assets/newbread13.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        types: "Multigrain bread",
        discount: '5%',
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 32,
        title: "Pretzel (Germany).",
        price: "143.99 € / piece",
        images: require("../assets/newbread14.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        types: "Pretzel (Germany).",
        discount: '5%',
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 33,
        title: "Multigrain bread.",
        price: "431.99 € / piece",
        images: require("../assets/newbread15.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Multigrain bread",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",


        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 34,
        title: "Damper (Australia) bread.",
        price: "1.43 € / piece",
        images: require("../assets/newbread16.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Damper (Australia) bread.",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 35,
        title: "Paratha (India/Pakistan).",
        price: "1.45 € / piece",
        images: require("../assets/newbread5.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        types: "Paratha (India/Pakistan).",
        discount: '5%',
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",


        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 36,
        title: "Tiger Bread (Netherlands).",
        price: "1.99 € / piece",
        images: require("../assets/newbread7.jpg"),
        kg: "~200 gr/piece",
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Tiger Bread (Netherlands).",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 37,
        title: "Pita bread",
        price: "178 € / piece",
        kg: "~200 gr/piece",
        images: require("../assets/newbread1.jpg"),
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Pita bread.",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 38,
        title: "Pita bread.",
        price: "178 € / piece",
        kg: "~200 gr/piece",
        images: require("../assets/newbread1.jpg"),
        descriptiontitle: "Spain",
        discount: '5%',
        types: "Pita bread.",
        description: "Doughs are usually baked, but in some cuisines breads are steamed (e.g., mantou), fried (e.g., puri), or baked on an unoiled frying pan (e.g., tortillas). It may be leavened or unleavened (e.g. matzo). Salt, fat and leavening agents such as yeast and baking soda are common ingredients, though bread may contain other ingredients, such as milk, egg, sugar, spice, fruit (such as raisins), vegetables (such as onion), nuts (such as walnut) or seeds (such as poppy).[35",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },


];