export const Vegtableslist = [
    {
        id: 1,
        title: "Boston Avocado Kiwi",
        price: "1.10 $/piece",
        kg: "~130 gr/piece",
        images: require("../assets/fr11.jpg"),
        description: "Instead of manually building out recipes for your website, you can rely on technology to do it. You don’t have to figure out the individual moving parts by yourself, like optimizing the desktop and mobile versions or calculating accurate nutritional values. An AI-powered platform could greatly simplify these tasks for you.",
        types: "Boston Avocado Kiwi",
        discount: '5%',
        descriptiontitle: "Spain",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 2,
        title: "Boston Avocado Kiwi",
        price: "1.10 $/piece",
        images: require("../assets/fr11.jpg"),
        kg: "~130 gr/piece",
        descriptiontitle: "Spain",
        types: "Boston Avocado Kiwi",
        description: "Instead of manually building out recipes for your website, you can rely on technology to do it. You don’t have to figure out the individual moving parts by yourself, like optimizing the desktop and mobile versions or calculating accurate nutritional values. An AI-powered platform could greatly simplify these tasks for you.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 3,
        title: "Boston Avocado Kiwi",
        price: "1.10 $/piece",
        images: require("../assets/fr11.jpg"),
        kg: "~130 gr/piece",
        descriptiontitle: "Spain",
        types: "Boston Avocado Kiwi",
        description: "Instead of manually building out recipes for your website, you can rely on technology to do it. You don’t have to figure out the individual moving parts by yourself, like optimizing the desktop and mobile versions or calculating accurate nutritional values. An AI-powered platform could greatly simplify these tasks for you.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 4,
        title: "Boston Avocado Kiwi",
        price: "1.10 $/piece",
        images: require("../assets/fr11.jpg"),
        kg: "~130 gr/piece",
        descriptiontitle: "Spain",
        types: "Boston Avocado Kiwi",
        description: "Instead of manually building out recipes for your website, you can rely on technology to do it. You don’t have to figure out the individual moving parts by yourself, like optimizing the desktop and mobile versions or calculating accurate nutritional values. An AI-powered platform could greatly simplify these tasks for you.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 5,
        title: "Boston Avocado Kiwi",
        price: "1.10 $/piece",
        images: require("../assets/fr11.jpg"),
        kg: "~130 gr/piece",
        descriptiontitle: "Spain",
        types: "Boston Avocado Kiwi",
        description: "Instead of manually building out recipes for your website, you can rely on technology to do it. You don’t have to figure out the individual moving parts by yourself, like optimizing the desktop and mobile versions or calculating accurate nutritional values. An AI-powered platform could greatly simplify these tasks for you.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 6,
        title: "Boston Avocado Kiwi",
        price: "1.85 € / piece",
        images: require("../assets/fr22.jpg"),
        kg: "~67 gr/piece",
        descriptiontitle: "Spain",
        types: "Boston Avocado Kiwi",
        description: "The art of recipe writing may be difficult to master, but it’s definitely not impossible to get right. Today’s recipe content ecosystem is rapidly growing and incredibly competitive. To have an edge over other content creators and make your recipes your audience’s go-to, you need to not only write an amazing recipe but also optimize it for both readers and technology. However, the process of setting up your recipe website doesn’t have to be as daunting as it looks. With an AI-powered solution like Whisk for Recipe Creators",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 7,
        title: "Raspberry Pear ",
        price: "1.85 € / piece",
        images: require("../assets/fr22.jpg"),
        kg: "~67 gr/piece",
        descriptiontitle: "Spain",
        types: "Raspberry Pear",
        description: "The art of recipe writing may be difficult to master, but it’s definitely not impossible to get right. Today’s recipe content ecosystem is rapidly growing and incredibly competitive. To have an edge over other content creators and make your recipes your audience’s go-to, you need to not only write an amazing recipe but also optimize it for both readers and technology. However, the process of setting up your recipe website doesn’t have to be as daunting as it looks. With an AI-powered solution like Whisk for Recipe Creators",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 8,
        title: "Raspberry Pear",
        price: "1.85 € / piece",
        images: require("../assets/fr22.jpg"),
        kg: "~67 gr/piece",
        descriptiontitle: "Spain",
        types: "Raspberry Pear",
        description: "The art of recipe writing may be difficult to master, but it’s definitely not impossible to get right. Today’s recipe content ecosystem is rapidly growing and incredibly competitive. To have an edge over other content creators and make your recipes your audience’s go-to, you need to not only write an amazing recipe but also optimize it for both readers and technology. However, the process of setting up your recipe website doesn’t have to be as daunting as it looks. With an AI-powered solution like Whisk for Recipe Creators",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 9,
        title: "Raspberry Pear",
        price: "1.85 € / piece",
        images: require("../assets/fr22.jpg"),
        kg: "~67 gr/piece",
        descriptiontitle: "Spain",
        types: "Raspberry Pear",
        description: "The art of recipe writing may be difficult to master, but it’s definitely not impossible to get right. Today’s recipe content ecosystem is rapidly growing and incredibly competitive. To have an edge over other content creators and make your recipes your audience’s go-to, you need to not only write an amazing recipe but also optimize it for both readers and technology. However, the process of setting up your recipe website doesn’t have to be as daunting as it looks. With an AI-powered solution like Whisk for Recipe Creators",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 10,
        title: "Raspberry Pear",
        price: "1.85 € / piece",
        images: require("../assets/fr22.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~67 gr/piece",
        types: "Raspberry Pear",
        descriptiontitle: "Spain",
        description: "The art of recipe writing may be difficult to master, but it’s definitely not impossible to get right. Today’s recipe content ecosystem is rapidly growing and incredibly competitive. To have an edge over other content creators and make your recipes your audience’s go-to, you need to not only write an amazing recipe but also optimize it for both readers and technology. However, the process of setting up your recipe website doesn’t have to be as daunting as it looks. With an AI-powered solution like Whisk for Recipe Creators",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 11,
        title: "Pomegranate",
        price: "1.45 € / piece",
        images: require("../assets/fr33.jpg"),
        kg: "~241 gr/piece",
        descriptiontitle: "Spain",
        types: "Pomegranate",
        description: "Nutritional data is another way to get Google to notice your recipe. But more importantly, this information helps your readers prioritize their health and dietary needs. You can perform this nutritional analysis using the USDA database..",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 12,
        title: "Nectarine",
        price: "1.78 € / piece",
        images: require("../assets/fr44.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Nectarine",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 13,
        title: "Nectarine",
        price: "1.78 € / piece",
        images: require("../assets/fr44.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Nectarine",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 14,
        title: "Orange",
        price: "1.57 € / piece",
        images: require("../assets/newfruit1.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Orange",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 15,
        title: "Red Delicious Apple",
        price: "1.90 € / piece",
        images: require("../assets/newfruit2.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Red Delicious Apple",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 16,
        title: "Lychee",
        price: "1.67 € / piece",
        images: require("../assets/newfruits3.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Lychee",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
       
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 17,
        title: "Papaya",
        price: "1.34 € / piece",
        images: require("../assets/newfruit5.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Papaya",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 18,
        title: "Endive Lettuce",
        price: "1.956 € / piece",
        images: require("../assets/newveg6.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Endive Lettuce",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 19,
        title: "Pineapple",
        price: "1.67 € / piece",
        images: require("../assets/newfruit7.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Pineapple",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 20,
        title: "Coconut",
        price: "199 € / piece",
        images: require("../assets/newveg8.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Coconut",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 21,
        title: "Coconut",
        price: "199 € / piece",
        images: require("../assets/newveg8.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Coconut",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 22,
        title: "Coconut",
        price: "199 € / piece",
        images: require("../assets/newveg8.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Coconut",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 23,
        title: "Tangerine",
        price: "1.399 € / piece",
        images: require("../assets/newveg9.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Tangerine",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 24,
        title: "Green Grapes",
        price: "143.99 € / piece",
        images: require("../assets/newfruit10.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Green Grapes",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 25,
        title: "Green Grapes",
        price: "143.99 € / piece",
        images: require("../assets/newfruit10.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Green Grapes",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 26,
        title: "Green Grapes",
        price: "143.99 € / piece",
        images: require("../assets/newfruit10.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Green Grapes",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 27,
        title: "Green Grapes",
        price: "143.99 € / piece",
        images: require("../assets/newfruit10.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Green Grapes",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 28,
        title: "Green Grapes",
        price: "143.99 € / piece",
        images: require("../assets/newfruit10.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Green Grapes",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 29,
        title: "Blackberry",
        price: "133.99 € / piece",
        images: require("../assets/newfruit11.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Blackberry",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 30,
        title: "Raspberry ",
        price: "144.99 € / piece",
        images: require("../assets/newfruit12.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Raspberry",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 31,
        title: "Persimmon",
        price: "10.99 € / piece",
        images: require("../assets/newfruit13.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Persimmon",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 32,
        title: "Apricot",
        price: "11.99 € / piece",
        images: require("../assets/newfruit14.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Apricot",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 33,
        title: "Mango",
        price: "21.99 € / piece",
        images: require("../assets/newfruit15.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Mango",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 34,
        title: "Peach",
        price: "31.99 € / piece",
        images: require("../assets/newfruit16.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Peach",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 35,
        title: "Peach",
        price: "31.99 € / piece",
        images: require("../assets/newfruit16.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Peach",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 36,
        title: "Peach",
        price: "31.99 € / piece",
        images: require("../assets/newfruit16.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Peach",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 37,
        title: "Peach",
        price: "31.99 € / piece",
        images: require("../assets/newfruit16.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Peach",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 38,
        title: "Peach",
        price: "31.99 € / piece",
        images: require("../assets/newfruit16.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Peach",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 39,
        title: "Eggplant",
        price: "41.99 € / piece",
        images: require("../assets/newfruit17.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Eggplant",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 40,
        title: "Cantaloupe",
        price: "51.99 € / piece",
        images: require("../assets/newfruit18.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Cantaloupe",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 41,
        title: "Cassava ",
        price: "61.99 € / piece",
        images: require("../assets/newfruit19.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Cassava",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
       
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 42,
        title: "Watermelon",
        price: "71.99 € / piece",
        images: require("../assets/newfruit20.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Watermelon",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 43,
        title: "Jackfruit ",
        price: "81.99 € / piece",
        images: require("../assets/newfruit21.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Jackfruit",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 44,
        title: "Cherry",
        price: "91.99 € / piece",
        images: require("../assets/newfruit25.jpg"),
        kg: "~133 gr/piece",
        descriptiontitle: "Spain",
        types: "Cherry",
        description: "Also known as “romance copy,” this is the short hook that informs and persuades the reader. In a rich search result, this supports the title (and accompanying image) with interesting additional information.",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

];