export const Vegtableslist = [
    {
        id: 1,
        title: "Best Chapli Kabab",
        price: "1.10 $/piece",
        kg: "~150 gr/piece",
        discount: "13%",
        images: require("../assets/homemade1.jpg"),
        types: 'Best Chapli Kabab',
        descriptiontitle: "Spain",
        description: " Try to visualize the title and any other subtitles in terms of HTML. Apart from improving search results, headings and subheadings (H1-H6) on your recipe page organize the content and help your readers scan quickly to find the most relevant parts first.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 2,
        title: "Best Chapli Kabab",
        price: "1.10 $/piece",
        images: require("../assets/homemade1.jpg"),
        discount: "3%",
        kg: "~150 gr/piece",
        types: 'Best Chapli Kabab',
        descriptiontitle: "Spain",
        description: " Try to visualize the title and any other subtitles in terms of HTML. Apart from improving search results, headings and subheadings (H1-H6) on your recipe page organize the content and help your readers scan quickly to find the most relevant parts first.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 3,
        title: "Best Chapli Kabab",
        price: "1.10 $/piece",
        images: require("../assets/homemade1.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~150 gr/piece",
        types: 'Best Chapli Kabab',
        discount: "31%",

        descriptiontitle: "Spain",
        description: " Try to visualize the title and any other subtitles in terms of HTML. Apart from improving search results, headings and subheadings (H1-H6) on your recipe page organize the content and help your readers scan quickly to find the most relevant parts first.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 4,
        title: "Best Chapli Kabab",
        price: "1.10 $/piece",
        images: require("../assets/homemade1.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~150 gr/piece",
        types: 'Best Chapli Kabab',
        discount: "32%",

        descriptiontitle: "Spain",
        description: " Try to visualize the title and any other subtitles in terms of HTML. Apart from improving search results, headings and subheadings (H1-H6) on your recipe page organize the content and help your readers scan quickly to find the most relevant parts first.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 5,
        title: " Cauliflower Panjeeri",
        price: "1.85 € / piece",
        images: require("../assets/homemade2.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~145 gr/piece",
        types: 'Cauliflower Panjeeri',
        discount: "35%",

        descriptiontitle: "Spain",
        description: "Your recipe for cookies must tell the reader how many cookies are in a batch. Just as in the ingredient list, this needs precise measurements. Ensure that an individual portion size is reasonable.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 6,
        title: "Dahi Bara",
        price: "1.45 € / piece",
        images: require("../assets/homemade3.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~123 gr/piece",
        types: 'Dahi Bara',
        discount: "35%",

        descriptiontitle: "Spain",
        description: "When you search for “chicken piccata recipe” on Google, you easily get more than 4.6 million results. How is the search engine collecting these relevant results? And how can you make sure your recipe has the right foundation to come out on top (i.e., on the first page)?",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 7,
        title: "Dahi Bara",
        price: "1.45 € / piece",
        images: require("../assets/homemade3.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~123 gr/piece",
        types: 'Dahi Bara',
        discount: "37%",

        descriptiontitle: "Spain",
        description: "When you search for “chicken piccata recipe” on Google, you easily get more than 4.6 million results. How is the search engine collecting these relevant results? And how can you make sure your recipe has the right foundation to come out on top (i.e., on the first page)?",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 8,
        title: "Dahi Bara",
        price: "1.45 € / piece",
        images: require("../assets/homemade3.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~123 gr/piece",
        types: 'Dahi Bara',
        discount: "38%",

        descriptiontitle: "Spain",
        description: "When you search for “chicken piccata recipe” on Google, you easily get more than 4.6 million results. How is the search engine collecting these relevant results? And how can you make sure your recipe has the right foundation to come out on top (i.e., on the first page)?",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 9,
        title: "Sarson Ka Saag",
        price: "1.99 € / piece",
        images: require("../assets/homemade4.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        types: 'Sarson Ka Saag',
        discount: "3%",

        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 10,
        title: "Teriyaki Chicken Bowl",
        price: "1.34 € / piece",
        images: require("../assets/newhomemade1.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        types: 'Teriyaki Chicken Bowl',
        discount: "3%",

        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 11,
        title: "Tomato Basil Bruschetta",
        price: "1.35 € / piece",
        images: require("../assets/newhomemade2.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        types: 'Tomato Basil Bruschetta',
        discount: "33%",

        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },

    {
        id: 12,
        title: "Chicken and Rice Casserole",
        price: "1.36 € / piece",
        images: require("../assets/newhomemade3.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "53%",
        types: 'Chicken and Rice Casserole',

        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 13,
        title: "Veggie Burger",
        price: "1.37 € / piece",
        images: require("../assets/newhomemade4.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "43%",
        types: 'Veggie Burger',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 14,
        title: "Garlic Butter Shrimp",
        price: "1.38 € / piece",
        images: require("../assets/newhomemade5.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "63%",
        types: 'Garlic Butter Shrimp',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 15,
        title: "Caprese  Avocado",
        price: "1.39 € / piece",
        images: require("../assets/newhomemade6.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "83%",
        types: 'Caprese  Avocado',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 16,
        title: "Caprese  Avocado",
        price: "1.39 € / piece",
        images: require("../assets/newhomemade6.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "63%",
        types: 'Caprese  Avocado',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",


        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 17,
        title: "Caprese  Avocado",
        price: "1.39 € / piece",
        images: require("../assets/newhomemade6.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "93%",
        types: 'Caprese  Avocado',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 18,
        title: "Caprese  Avocado",
        price: "1.39 € / piece",
        images: require("../assets/newhomemade6.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "43%",
        types: 'Caprese  Avocado',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },

    {
        id: 19,
        title: "Minestrone Soup",
        price: "1.20 € / piece",
        images: require("../assets/newhomemade7.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "55%",
        types: 'Minestrone Soup',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },

    {
        id: 20,
        title: "Buffalo Chicken Wings",
        price: "1.21 € / piece",
        images: require("../assets/newhomemade8.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "66%",
        types: 'Buffalo Chicken Wings',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 21,
        title: "Buffalo Chicken Wings",
        price: "1.22 € / piece",
        images: require("../assets/newhomemade9.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "76%",
        types: 'Buffalo Chicken Wings',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 22,
        title: "Sweet Potato Casserole",
        price: "1.22 € / piece",
        images: require("../assets/newhomemade9.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "34%",
        types: 'Sweet Potato Casserole',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 23,
        title: "Lemon Garlic Roasted Chicken",
        price: "1.23 € / piece",
        images: require("../assets/newhomemade10.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "89%",
        types: 'Lemon Garlic Roasted Chicken',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 24,
        title: "Zucchini Noodles with Pesto",
        price: "1.24 € / piece",
        images: require("../assets/newhomemade11.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "45%",
        types: 'Zucchini Noodles with Pesto',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 25,
        title: "Sausage and Peppers",
        price: "1.34 € / piece",
        images: require("../assets/newhomemade12.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "39%",
        types: 'Sausage and Peppers',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },

    {
        id: 26,
        title: "Cauliflower Pizza",
        price: "1.66 € / piece",
        discount: "20%",
        types: 'Cauliflower Pizza',
        images: require("../assets/newhomemade13.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 27,
        title: "Shrimp Fried Rice",
        price: "1.67 € / piece",
        images: require("../assets/newhomemade14.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "23%",
        types: 'Shrimp Fried Rice',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 28,
        title: "Sarson Ka Saag",
        price: "1.68 € / piece",
        images: require("../assets/newhomemade15.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "23%",
        types: 'Sarson Ka Saag',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },

    {
        id: 29,
        title: "Chicken Tacos",
        price: "1.69 € / piece",
        images: require("../assets/newhomemade16.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "90%",
        types: 'Chicken Tacos',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 30,
        title: "Lentil Soup",
        price: "1.91 € / piece",
        images: require("../assets/newhomemade17.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "67%",
        types: 'Lentil Soup',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 31,
        title: "Quinoa Salad",
        price: "1.92 € / piece",
        images: require("../assets/newfruit18.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "30%",
        types: 'Quinoa Salad',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 32,
        title: "Spinach and Feta Stuffed Chick",
        price: "1.93 € / piece",
        images: require("../assets/newhomemade19.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "30%",
        types: 'Spinach and Feta Stuffed Chick',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 33,
        title: "Tofu Pad Thai",
        price: "1.94 € / piece",
        images: require("../assets/newhomemade20.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "30%",
        types: 'Tofu Pad Thai',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },

    {
        id: 34,
        title: "Beef and Broccoli",
        price: "1.909 € / piece",
        images: require("../assets/newhomemade21.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "30%",
        types: 'Beef and Broccoli',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 35,
        title: "Chicken Parmesan",
        price: "1.994 € / piece",
        images: require("../assets/newhomemade22.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "30%",
        types: 'Chicken Parmesan',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 36,
        title: "Chicken Parmesan",
        price: "1.994 € / piece",
        images: require("../assets/newhomemade22.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        discount: "30%",
        types: 'Chicken Parmesan',
        descriptiontitle: "Spain",
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 37,
        title: "Chicken Parmesan",
        price: "1.994 € / piece",
        images: require("../assets/newhomemade22.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "30%",
        types: 'Chicken Parmesan',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 38,
        title: "Chicken Parmesan",
        price: "1.994 € / piece",
        images: require("../assets/newhomemade22.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "30%",
        types: 'Chicken Parmesan',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 39,
        title: "Chicken Parmesan",
        price: "1.994 € / piece",
        images: require("../assets/newhomemade22.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "30%",
        types: 'Chicken Parmesan',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 40,
        title: "Sarson Ka Saag",
        price: "1.81 € / piece",
        images: require("../assets/newhomemade24.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "30%",
        types: 'Sarson Ka Saag',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 41,
        title: "Chicken Alfredo",
        price: "1.82 € / piece",
        images: require("../assets/newhomemade25.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "30%",
        types: 'Chicken Alfredo',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 42,
        title: "Chicken Alfredo",
        price: "1.82 € / piece",
        images: require("../assets/newhomemade25.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "30%",
        types: 'Chicken Alfredo',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 43,
        title: "Chicken Alfredo",
        price: "1.82 € / piece",
        images: require("../assets/newhomemade25.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "30%",
        types: 'Best Chapli Kabab',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 44,
        title: "Chicken Alfredo",
        price: "1.82 € / piece",
        images: require("../assets/newhomemade25.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "30%",
        types: 'Chicken Alfredo',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 45,
        title: "Chicken Alfredo",
        price: "1.82 € / piece",
        images: require("../assets/newhomemade25.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "30%",
        types: 'Chicken Alfredo',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 46,
        title: "Chicken Alfredo",
        price: "1.82 € / piece",
        images: require("../assets/newhomemade25.jpg"),
        iconshop: require("../assets/shopping-cart.png"),
        iconfavor: require("../assets/heart.png"),
        kg: "~176 gr/piece",
        descriptiontitle: "Spain",
        discount: "30%",
        types: 'Chicken Alfredo',
        description: "Structured data involves implementing a markup on your web page, which provides additional information about a page and classifies the page’s content. This enhances search engines’ understanding of the content. The better search engines understand the content, the higher the chances are that you will rank in search. For this markup to be consistently recognized and parsed by search engines, it needs to follow certain universal conventions.",

        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },



];