export const Vegtableslist = [
    {
        id: 1,
        title: "Gulab jamun",
        price: "1.10 $/piece",
        kg: "~180 gr/piece",
        images: require("../assets/sweet1.jpg"),
        discount: '5%',
        descriptiontitle: "Spain",
        types: 'Gulab jamun',
        description: "Sweet can be an adjective or a noun. It can describe something pleasing to the senses, like a sweet song, or when you're playing basketball and get nothing but net. Sweet! As a noun, it's a confection, a little something for dessert. ",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 2,
        title: "Purple  Chum Chum",
        price: "31.85 € / piece",
        images: require("../assets/sweet2.jpg"),
        kg: "~150 gr/piece",
        descriptiontitle: "Spain",
        types: 'Purple  Chum Chum',
        description: "A little sweet inspiration goes a long way, so here are some captions and quotes that you can freely affix to your resplendent photos of desserts.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 3,
        title: "Purple  Chum Chum",
        price: "31.85 € / piece",
        images: require("../assets/sweet2.jpg"),

        kg: "~150 gr/piece",
        descriptiontitle: "Spain",
        types: 'Purple  Chum Chum',
        description: "A little sweet inspiration goes a long way, so here are some captions and quotes that you can freely affix to your resplendent photos of desserts.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 4,
        title: "Purple  Chum Chum",
        price: "31.85 € / piece",
        images: require("../assets/sweet2.jpg"),
        types: 'Purple  Chum Chum',
        kg: "~150 gr/piece",
        descriptiontitle: "Spain",
        description: "A little sweet inspiration goes a long way, so here are some captions and quotes that you can freely affix to your resplendent photos of desserts.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 5,
        title: "Purple  Chum Chum",
        price: "31.85 € / piece",
        images: require("../assets/sweet2.jpg"),
        types: 'Purple  Chum Chum',
        kg: "~150 gr/piece",
        descriptiontitle: "Spain",
        description: "A little sweet inspiration goes a long way, so here are some captions and quotes that you can freely affix to your resplendent photos of desserts.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 6,
        title: "Purple  Chum Chum",
        price: "31.85 € / piece",
        images: require("../assets/sweet2.jpg"),
        types: 'Purple  Chum Chum',
        kg: "~150 gr/piece",
        descriptiontitle: "Spain",
        description: "A little sweet inspiration goes a long way, so here are some captions and quotes that you can freely affix to your resplendent photos of desserts.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 7,
        title: "Purple Rabri Chocolate",
        price: "12.45 € / piece",
        images: require("../assets/sweet3.jpg"),
        types: 'Purple Rabri Chocolate',
        kg: "~34 gr/piece",
        descriptiontitle: "Spain",
        description: "Food that’s sweet is full of sugar, bad for your teeth, but oh so tasty. People who are sweet are super nice, like that sweet lunch lady who gives you an extra cookie.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 8,
        title: "Purple Rabri Chocolate",
        price: "1.299 € / piece",
        images: require("../assets/newsweet1.jpg"),
        types: 'Purple Rabri Chocolate',
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 9,
        title: "Sohan Halwa",
        price: "1.299 € / piece",
        images: require("../assets/newsweet1.jpg"),
        types: 'Sohan Halwa',
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 10,
        title: "Sohan Halwa",
        price: "1.299 € / piece",
        images: require("../assets/newsweet1.jpg"),
        types: 'Sohan Halwa',
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 11,
        title: "Sohan Halwa",
        price: "1.299 € / piece",
        images: require("../assets/newsweet1.jpg"),
        types: 'Sohan Halwa',
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,



    },
    {
        id: 12,
        title: "Sohan Halwa",
        price: "1.299 € / piece",
        images: require("../assets/newsweet1.jpg"),
        types: 'Sohan Halwa',
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 13,
        title: "Kheer",
        price: "1.199 € / piece",
        images: require("../assets/newsweet2.jpg"),
        types: 'Kheer',
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 14,
        title: "Turkish Delight",
        price: "1.099 € / piece",
        images: require("../assets/newsweet3.jpg"),
        types: 'Turkish Delight',
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 15,
        title: "Turkish Delight",
        price: "1.099 € / piece",
        images: require("../assets/newsweet3.jpg"),
        types: 'Turkish Delight',
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 16,
        title: "Turkish Delight",
        price: "1.099 € / piece",
        images: require("../assets/newsweet3.jpg"),
        types: 'Turkish Delight',
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 17,
        title: "Licorice",
        price: "1.019 € / piece",
        images: require("../assets/newsweet4.jpg"),
        types: 'Licorice',
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 18,
        title: "Cotton Candy",
        price: "1.09 € / piece",
        images: require("../assets/newsweet5.jpg"),
        kg: "~89 gr/piece",
        types: 'Cotton Candy',
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 19,
        title: "Cannoli",
        price: "1.19 € / piece",
        images: require("../assets/newsweet6.jpg"),
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        types: 'Cannoli',
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 20,
        title: "Cheesecake",
        price: "1.29 € / piece",
        images: require("../assets/newsweet7.jpg"),
        kg: "~89 gr/piece",
        types: 'Cheesecake',
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 21,
        title: "Nougat",
        price: "1.39 € / piece",
        images: require("../assets/newsweet8.jpg"),
        kg: "~89 gr/piece",
        types: 'Nougat',
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 22,
        title: "Nougat",
        price: "1.39 € / piece",
        images: require("../assets/newsweet8.jpg"),
        kg: "~89 gr/piece",
        types: 'Nougat',
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 23,
        title: "Nougat",
        price: "1.39 € / piece",
        images: require("../assets/newsweet8.jpg"),
        kg: "~89 gr/piece",
        types: 'Nougat',
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 24,
        title: "Chocolava Cake",
        price: "1.49 € / piece",
        images: require("../assets/newsweet9.jpg"),
        kg: "~89 gr/piece",
        types: 'Chocolava Cake',
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 25,
        title: "Beignets",
        price: "1.59 € / piece",
        images: require("../assets/newsweet10.jpg"),
        kg: "~89 gr/piece",
        types: 'Beignets',
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,


    },
    {
        id: 26,
        title: "Kulfi",
        price: "1.69 € / piece",
        images: require("../assets/newsweet11.jpg"),
        kg: "~89 gr/piece",
        types: 'Kulfi',
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 27,
        title: "Halwa",
        price: "1.79 € / piece",
        images: require("../assets/newsweet12.jpg"),
        kg: "~89 gr/piece",
        types: 'Halwa',
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 28,
        title: "Sacher Torte",
        price: "1.89 € / piece",
        images: require("../assets/newsweet13.jpg"),
        kg: "~89 gr/piece",
        types: 'Sacher Torte',
        descriptiontitle: "Spain",
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 29,
        title: "Jaggery Candy",
        price: "1.97 € / piece",
        images: require("../assets/newsweet14.jpg"),
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        types: 'Jaggery Candy',
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 30,
        title: "Pastel de Nata",
        price: "1.98 € / piece",
        images: require("../assets/newsweet12.jpg"),
        kg: "~89 gr/piece",
        descriptiontitle: "Spain",
        types: 'Pastel de Nata',
        description: "The poet Khalil Gibran said, “Friendship is always a sweet responsibility, never an opportunity.” Don’t opportunistically take your friends for granted, or you could become the target of some sweet revenge.",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred: require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },


];