export const Vegtableslist = [
    {
        id: 1,
        title: 'Boston Lettuce',
        price: '18.90 $',
        kg: "~432 gr/piece",
        images: require("../assets/vegone.png"),
        discount: '5%',
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'Boston Lettuce',
        descriptiontitle: "Spain",
        
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 2,
        title: 'Boston Lettuce',
        price: '18.90 $',
        kg: "~32 gr/piece",
        images: require("../assets/vegone.png"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'Boston Lettuce',
        discount: '5%',
        descriptiontitle: "New-Yourk",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
    {
        id: 3,
        title: 'Asparagus',
        price: '10.340 $',
        kg: "~432 gr/piece",
        images: require("../assets/vegtwo.png"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'Asparagus',
        discount: '5%',
        descriptiontitle: "Pakistan",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 4,
        title: 'Purple Cauliflower',
        price: '189.0 $',
        kg: "~43 gr/piece",
        images: require("../assets/vegthree.png"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'Purple Cauliflower',
        discount: '10%',
        descriptiontitle: "India",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 5,
        title: 'Purple Carrot',
        price: '32.40$',
        kg: "~432 gr/piece",
        images: require("../assets/newveg10.jpg"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'Purple Carrot',
        discount: '10%',
        descriptiontitle: "Bangladesh",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 6,
        title: 'Okra',
        price: '12.40$',
        kg: "~432 gr/piece",
        images: require("../assets/newveg2222.jpg"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'Okra',
        discount: '8%',
        descriptiontitle: "Srilanka",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 7,
        title: 'Green Onion',
        price: '65.40$',
        kg: "~432 gr/piece",
        images: require("../assets/newveg9.jpg"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'Green Onion',
        discount: ' 3%',
        descriptiontitle: "Canada",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 8,
        title: 'Mushroom',
        price: '65.40$',
        kg: "~432 gr/piece",
        images: require("../assets/newveg8.jpg"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'Mushroom',
        discount: ' 23%',
        descriptiontitle: "America",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 9,
        title: 'Pumpkin',
        price: '65.40$',
        kg: "~432 gr/piece",
        images: require("../assets/newveg9.jpg"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'Pumpkin',
        discount: '13%',
        descriptiontitle: "Roose",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 10,
        title: 'tomato',
        price: '65.40$',
        kg: "~432 gr/piece",
        images: require("../assets/newveg11.jpg"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'tomato',
        discount: ' 3%',
        descriptiontitle: "Al-Jeeria",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 11,
        title: 'tomato',
        price: '65.40$',
        kg: "~432 gr/piece",
        images: require("../assets/newveg11.jpg"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'tomato',
        discount: ' 3%',
        descriptiontitle: "Indonesia",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 12,
        title: 'tomato',
        price: '65.40$',
        kg: "~432 gr/piece",
        images: require("../assets/newveg11.jpg"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'tomato',
        discount: ' 3%',
        descriptiontitle: "pakistan",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,
    },
    {
        id: 13,
        title: 'Tomato',
        price: '65.40$',
        kg: "~432 gr/piece",
        images: require("../assets/newveg11.jpg"),
        description:
            'Vegetables are organized into 5 subgroups based on their nutrients: dark green; red and orange; beans, peas, and lentils; starchy; and other vegetables. Image.',
        types: 'Tomato',
        discount: ' 3%',
        descriptiontitle: "Iran",
        shoppingcard: require("../assets/shopping-cart.png"),
        heartfavourite: require("../assets/heart.png"),
        filledheartred:require("../assets/heartpngred.jpg"),
        cartQuantity: 0,
        favourite: false,

    },
];
